export const CREATE_STREAM = 'CREATE_STREAM';

export const CREATE_QUIZ = 'CREATE_QUIZ';
export const CLOSE_QUIZ = 'CLOSE_QUIZ';
export const OPEN_QUIZ = 'OPEN_QUIZ';

export const CLOSE_ANSWER = 'CLOSE_ANSWER';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';

export const UPDATE_VIDEOS = 'UPDATE_VIDEOS';
